// Precomputes US state SVG paths for the mobile coverage map so the app
// doesn't need d3/topojson/us-atlas at runtime. Re-run only if the map
// projection or size changes:  npx tsx scripts/generate-us-paths.ts
import { writeFileSync } from "node:fs";
import { geoAlbersUsa, geoPath } from "d3-geo";
import { feature } from "topojson-client";
import type { GeometryCollection, Topology } from "topojson-specification";
import us from "us-atlas/states-10m.json";

const topology = us as unknown as Topology;
const states = feature(topology, topology.objects.states as GeometryCollection<{ name: string }>);
const toPath = geoPath(geoAlbersUsa().scale(1100).translate([450, 280])).digits(1);

type Pt = [number, number];

// Douglas–Peucker: a phone-sized map doesn't need 10m detail.
const EPSILON = 0.9; // px in the 900x560 viewBox
function simplifyRing(pts: Pt[]): Pt[] {
  if (pts.length < 3) return pts;
  const [a, b] = [pts[0], pts[pts.length - 1]];
  let idx = -1;
  let max = 0;
  for (let i = 1; i < pts.length - 1; i++) {
    const [x, y] = pts[i];
    const dx = b[0] - a[0];
    const dy = b[1] - a[1];
    const len = Math.hypot(dx, dy);
    const dist = len === 0 ? Math.hypot(x - a[0], y - a[1]) : Math.abs(dy * x - dx * y + b[0] * a[1] - b[1] * a[0]) / len;
    if (dist > max) {
      max = dist;
      idx = i;
    }
  }
  if (max <= EPSILON) return [a, b];
  return [...simplifyRing(pts.slice(0, idx + 1)).slice(0, -1), ...simplifyRing(pts.slice(idx))];
}

// Tiny islands (Aleutians, Keys, barrier islands) are invisible at phone
// size but dominate the byte count, so only the biggest rings and any ring
// over MIN_AREA px² are kept (the largest always stays, e.g. D.C.).
const MIN_AREA = 12;
const round = (n: number) => Math.round(n * 10) / 10;

function simplifyPath(d: string): string {
  const rings = d.split("M").filter(Boolean).map((seg) =>
    seg.replace(/Z$/, "").split("L").map((p) => p.split(",").map(Number) as Pt),
  );
  const area = (r: Pt[]) => {
    let s = 0;
    for (let i = 0; i < r.length; i++) {
      const [x1, y1] = r[i];
      const [x2, y2] = r[(i + 1) % r.length];
      s += x1 * y2 - x2 * y1;
    }
    return Math.abs(s / 2);
  };
  const sized = rings.map((r) => ({ r, a: area(r) }));
  const biggest = Math.max(...sized.map((s) => s.a));
  return sized
    .filter((s) => s.a >= MIN_AREA || s.a === biggest)
    .map(({ r }) => {
      const closed = simplifyRing([...r, r[0]]).slice(0, -1);
      return "M" + closed.map(([x, y]) => `${round(x)},${round(y)}`).join("L") + "Z";
    })
    .join("");
}

const paths: Record<string, string> = {};
for (const f of states.features) {
  const d = toPath(f);
  if (d) paths[f.properties.name] = simplifyPath(d);
}

const out = `// GENERATED by scripts/generate-us-paths.ts — do not edit by hand.
// State outlines projected into a 900x560 viewBox (Albers USA).
export const US_MAP_VIEWBOX = "0 0 900 560";
export const US_STATE_PATHS: Record<string, string> = ${JSON.stringify(paths)};
`;
writeFileSync("apps/mobile/src/lib/us-state-paths.ts", out);
console.log(Object.keys(paths).length, "states,", Math.round(out.length / 1024), "KB");
